language:
  - cpp

before_install:
  - sudo add-apt-repository -y ppa:team-xbmc/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y libegl1-mesa-dev
  - sudo apt-get install -y libgles2-mesa-dev
  - sudo apt-get install -y libsdl2-dev
  
script:
  - g++ -o draw_line dda.cpp -I /usr/include/SDL2/ -lSDL2

after_success: 
- bash <(curl -s https://codecov.io/bash)
